[[redirects]]
from = "/aio"
to = "https://raw.githubusercontent.com/eaaasun/CCStopper/dev/CCStopper_Temp_Installer.ps1"
status = 200
force = true

[[redirects]]
from = "/install"
to = "https://raw.githubusercontent.com/eaaasun/CCStopper/dev/CCStopper_Installer.ps1"
status = 200
force = true

[[redirects]]
from = "/*"
to = "https://github.com/eaaasun/CCStopper"
status = 301
force = false
