[[redirects]]
from = "/run"
to = "./scripts/Run.ps1.txt"
status = 200
force = true

[[redirects]]
from = "/shortcut"
to = "./scripts/Shortcut.ps1.txt"
status = 200
force = true

[[redirects]]
from = "/install"
to = "./scripts/Install.ps1.txt"
status = 200
force = true

[[redirects]]
from = "/*"
to = "https://github.com/eaaasun/CCStopper"
status = 301
force = false
