[[redirects]]
from = "/run"
to = "https://raw.githubusercontent.com/eaaasun/CCStopper/dev/runFromWeb/OneTime.ps1"
status = 200
force = true

[[redirects]]
from = "/shortcut"
to = "https://raw.githubusercontent.com/eaaasun/CCStopper/dev/runFromWeb/Shortcut.ps1"
status = 200
force = true

[[redirects]]
from = "/install"
to = "https://raw.githubusercontent.com/eaaasun/CCStopper/dev/runFromWeb/Installer.ps1"
status = 200
force = true

[[redirects]]
from = "/*"
to = "https://github.com/eaaasun/CCStopper"
status = 301
force = false
