[[redirects]]
from = "/test"
to = "https://raw.githubusercontent.com/eaaasun/CCStopper/main/makezip.ps1"
status = 200
force = true

[[redirects]]
from = "/*"
to = "https://github.com/eaaasun/CCStopper"
status = 301
force = false
