[[redirects]]
from = "/*"
to = "https://github.com/eaaasun/CCStopper"
status = 404
force = false

[[redirects]]
from = "/test"
to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
status = 200
force = true
